@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title "Digital Wallet"

Person(client, "Client", "Digital Wallet user")
System(wallet, "Digital Wallet System", "Digital Wallet")

System_Ext(secret_manager, "AWS Secrets Manager", "Credentials Manager")
System_Ext(apm, "APM", "Application Performance Monitoring")
System_Ext(collect, "OTEL", "OpenTelemetry Collector")
System_Ext(payment_gateway, "Payment Gateway", "Payment processor")


Rel(client, wallet, "Uses", "HTTPS")
Rel(wallet, secret_manager, "Uses", "HTTPS")
Rel(wallet, apm, "Uses", "HTTPS")
Rel(wallet, collect, "Uses", "HTTPS")
Rel(wallet, payment_gateway, "Uses", "HTTPS")

@enduml