@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
AddRelTag("async", $lineStyle = DashedLine())

title "Digital Wallet"

Person(client, "Client", "Digital Wallet user")

System_Ext(payment_gateway, "Payment Gateway", "Payment processor")

System_Boundary(digital_wallet, "Digital Wallet") {
    Container(spa, "SPA", "React", "Digital Wallet Web App")
    Container(wallet_core, "Wallet Core", "TS", "Wallet Core is responsible for the transactions")
    Container(balance_service, "Balance Microservice", "TS", "Returns customer balance")
    Container(statement_service, "Statement Microservice", "TS", "Returns customer statements")
    Container(payment_acl, "Payment ACL", "TS", "Anticorruption Layer for Payment Gateway")

    ContainerDb(wallet_core_db, "Wallet Core DB", "MySQl")
    Rel(wallet_core, wallet_core_db, "Uses", "Mysql Driver")

    ContainerDb(balance_service_db, "Balance DB", "MySQl")
    Rel(balance_service, balance_service_db, "Uses", "Mysql Driver")

    ContainerDb(statement_service_db, "Statement DB", "MySQl")
    Rel(statement_service, statement_service_db, "Uses", "Mysql Driver")

    ContainerDb(payment_acl_db, "Payment ACL DB", "MySQl")
    Rel(payment_acl, payment_acl_db, "Uses", "Mysql Driver")

    Rel(client, spa, "Uses", "HTTPS")
    Rel(spa, wallet_core, "Uses", "JSON/HTTPS")
    Rel(spa, balance_service, "Uses", "JSON/HTTPS")
    Rel(spa, statement_service, "Uses", "JSON/HTTPS")
    Rel(wallet_core, payment_acl, "Uses", "JSON/HTTPS")
    Rel(payment_acl, payment_gateway, "Uses", "JSON/HTTPS")

    Rel(wallet_core, balance_service, "Topic", $tags = "async")
    Rel(wallet_core, statement_service, "Topic", $tags = "async")
}




@enduml